server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul:
      host: 192.168.26.48
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true # 开启心跳检测
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service           #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - My=diamond                            # 自定义断言，用户请求地址中的请求参数需要携带userType为diamond，才能经过网关断言
          filters:
            - My=li                                 # 自定义过滤器
        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service           #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由