server:
  port: 8080
  servlet:
    context-path: /lock


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: 2648
  redis:
    host: 192.168.26.48

mybatis-plus:
  type-aliases-package: com.li
  mapper-locations: classpath:mapper/*.xml
